/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetsIndexRouteImport } from './routes/bets/index'
import { Route as InviteUsernameRouteImport } from './routes/invite/$username'
import { Route as FriendsFriendIdRouteImport } from './routes/friends/$friendId'
import { Route as BetsCreateRouteImport } from './routes/bets/create'
import { Route as BetsBetIdRouteImport } from './routes/bets/$betId'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthSignupSplatRouteImport } from './routes/auth/signup/$'
import { Route as AuthLoginSplatRouteImport } from './routes/auth/login/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsIndexRoute = BetsIndexRouteImport.update({
  id: '/bets/',
  path: '/bets/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteUsernameRoute = InviteUsernameRouteImport.update({
  id: '/invite/$username',
  path: '/invite/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/$friendId',
  path: '/$friendId',
  getParentRoute: () => FriendsRoute,
} as any)
const BetsCreateRoute = BetsCreateRouteImport.update({
  id: '/bets/create',
  path: '/bets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsBetIdRoute = BetsBetIdRouteImport.update({
  id: '/bets/$betId',
  path: '/bets/$betId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignupRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLoginRoute,
} as any)
const AuthSignupSplatRoute = AuthSignupSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignupRoute,
} as any)
const AuthLoginSplatRoute = AuthLoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/create': typeof BetsCreateRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/invite/$username': typeof InviteUsernameRoute
  '/bets': typeof BetsIndexRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/signup/$': typeof AuthSignupSplatRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/create': typeof BetsCreateRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/invite/$username': typeof InviteUsernameRoute
  '/bets': typeof BetsIndexRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/signup/$': typeof AuthSignupSplatRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/create': typeof BetsCreateRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/invite/$username': typeof InviteUsernameRoute
  '/bets/': typeof BetsIndexRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/signup/$': typeof AuthSignupSplatRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/bets/$betId'
    | '/bets/create'
    | '/friends/$friendId'
    | '/invite/$username'
    | '/bets'
    | '/auth/login/$'
    | '/auth/signup/$'
    | '/auth/login/'
    | '/auth/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/bets/$betId'
    | '/bets/create'
    | '/friends/$friendId'
    | '/invite/$username'
    | '/bets'
    | '/auth/login/$'
    | '/auth/signup/$'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/bets/$betId'
    | '/bets/create'
    | '/friends/$friendId'
    | '/invite/$username'
    | '/bets/'
    | '/auth/login/$'
    | '/auth/signup/$'
    | '/auth/login/'
    | '/auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  BetsBetIdRoute: typeof BetsBetIdRoute
  BetsCreateRoute: typeof BetsCreateRoute
  InviteUsernameRoute: typeof InviteUsernameRoute
  BetsIndexRoute: typeof BetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/': {
      id: '/bets/'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof BetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$username': {
      id: '/invite/$username'
      path: '/invite/$username'
      fullPath: '/invite/$username'
      preLoaderRoute: typeof InviteUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof FriendsRoute
    }
    '/bets/create': {
      id: '/bets/create'
      path: '/bets/create'
      fullPath: '/bets/create'
      preLoaderRoute: typeof BetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/$betId': {
      id: '/bets/$betId'
      path: '/bets/$betId'
      fullPath: '/bets/$betId'
      preLoaderRoute: typeof BetsBetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthSignupRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthLoginRoute
    }
    '/auth/signup/$': {
      id: '/auth/signup/$'
      path: '/$'
      fullPath: '/auth/signup/$'
      preLoaderRoute: typeof AuthSignupSplatRouteImport
      parentRoute: typeof AuthSignupRoute
    }
    '/auth/login/$': {
      id: '/auth/login/$'
      path: '/$'
      fullPath: '/auth/login/$'
      preLoaderRoute: typeof AuthLoginSplatRouteImport
      parentRoute: typeof AuthLoginRoute
    }
  }
}

interface FriendsRouteChildren {
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
}

const FriendsRouteChildren: FriendsRouteChildren = {
  FriendsFriendIdRoute: FriendsFriendIdRoute,
}

const FriendsRouteWithChildren =
  FriendsRoute._addFileChildren(FriendsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  BetsBetIdRoute: BetsBetIdRoute,
  BetsCreateRoute: BetsCreateRoute,
  InviteUsernameRoute: InviteUsernameRoute,
  BetsIndexRoute: BetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
